### ISSUE TITLE
graceful enrichment

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-laravel#1]

**Comment by Cederman** [comment]
Any updates on this feature? It would really help me when shipping my product since everything that the Activity Trait is tracking could be deleted (thus should not be shown in the feed). On another note, wouldn't it be good to show this in the feed too. Instead of just removing it entirely?

For example, if an object is removed in the DB the feed would show something like "X deleted", and/or the earlier entry now has a "(deleted)" appended to it.

**Comment by tbarbugli** [comment]
@Cederman the feature was added on 2.1.2 For non standard behaviour (skip non enriched activities) it is possible now to detect non enriched activities via the ->enriched method

**Comment by Cederman** [comment]
@tbarbugli I can't seem how to apply this method. Can you guide me a bit?

I produce my enriched activities feed like this and in my view I get "Call to a member function enriched() on a non-object":

		$flatFeed = FeedManager::getNewsFeeds(1)['aggregated'];
		$enricher = new Enrich;
		$activities_all = $flatFeed->getActivities(0,25)['results'];
		$activities_all = $enricher->enrichAggregatedActivities($activities_all);
		$activities = [];

		foreach($activities_all as $activity) {
			if(is_array($activity) && $activity->enriched()) {
				array_push($activities, $activity);
			}
		}

Am I missing something?

**Comment by tbarbugli** [comment]
are you running on the latest version?

**Comment by Cederman** [comment]
Yes, version 2.2

**Comment by tbarbugli** [comment]
in latest versions of the library we annotate an enriched method to
activities. the method allows you to make sure the activity was correctly
enriched and handle failures without adding too much complexity to your
views or controller. The method is present on activities but not on
aggregated activities (aggregated activities are not directly enriched).

to quote your code, you should perform the check on this activities
$activities_all[]['activities'][],
not on $activities_all[]

Let me know if this is unclear of it this really does not work for you.

**Comment by Cederman** [comment]
@tbarbugli I don't really get the pseudocode you are writing. What in my code am I supposed to change?

This doesn't make sense to me:

		$activities_all[]['activities'][]

**Comment by tbarbugli** [comment]
What I wanted to say is that activities such as
$activities_all[0]['activities'] have the enriched method, you should check
if those are enriched, not the "top-level" activities (eg.
$activities_all[0]).

Is there a specific reason for you not to use the
stream-laravel::render_activity view tag? You could use that tag (or
something similar to it) to display the aggregated activities

eg.

// $activities is the result of
$enricher->enrichAggregatedActivities($activities_all);

@foreach ($activities as $aggregated)
@foreach ($aggregated['activities'] as $activity)
@include('stream-laravel::render_activity', array('activity'=>$activity))
@endforeach
@endforeach

Let me know if this makes sense for you.

**Comment by Cederman** [comment]
Actually, If I take a step back. The problem I initially had was that I can't seem to use my own file for rendering (i.e. the "render_activity" file). I have my own which does not output the:

    Log::warning('The activity could not be rendered, the following field/refs could not be enriched:', $activity->getNotEnrichedData());

But it always loads the vendor-supplied file. I tried removing the namespace but it still refuses to load it.

Guess my problem lies there ;)
