### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by LeventeNagy** [GetStream/stream-laravel#11]
Laravel 5 has been released, and my mistake, when i try to install it via composer  with Laravel 5 i get the following error

<pre>
    - get-stream/stream-laravel 2.1.1 requires illuminate/database 4.2.* -> sati
sfiable by illuminate/database[v4.2.1, v4.2.12, v4.2.16, v4.2.2, v4.2.3, v4.2.4,
 v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
</pre>

Will any updates will be available in the future?

Thank you

**Comment by tbarbugli** [comment]
Hi,
I am going to have a look at this somewhere this week. If nothing major breaks with Laravel 5 we should be able to release a compatible version soon. If you have time and feel like it, you can try to update the requirements in stream-laravel  (something like >= 4.2) and see what breaks, that would speed up things for sure :)

**Comment by LeventeNagy** [comment]
Okay sure will do it, will send feedback soon
