### ISSUE TITLE
Notifications are always zero

### ISSUE THREAD

**Issue by MoZart182** [GetStream/stream-laravel#17]
Hi,

I tested and all methods work properly. Only the method getNotificationFeed () is giving me problems. I have two test users, which one follows the other and the other way around too. But any ID to put you in the method, always returns zero notifications.

What am I doing wrong? or what is the problem?

**Comment by tbarbugli** [comment]
are you sending activities to the notification feed? this is usually using the method activityNotify, if you implemented that, please share the relevant code

**Comment by MoZart182** [comment]
This is my code:

```
$feeds = FeedManager::getUserFeed($user_ud = 1);
$feeds = FeedManager::getNotificationFeed($user_ud = 1);
echo '<pre>'; print_r($feeds->getActivities(0, 5) ); echo '</pre>';
```

And the response is:

```
Array
(
    [duration] => 22ms
    [next] => 
    [results] => Array
        (
        )

    [unread] => 0
    [unseen] => 0
)
```

**Comment by tbarbugli** [comment]
perhaps you are not sending data to the notification feed. do you send data there directly or via  the activityNotify method?

**Comment by MoZart182** [comment]
I do not understand. I think this method activityNotify not defined in the package. Could you give an example of use? Because, in the documentation nor is there a clear example. Thank you very much.

**Comment by tbarbugli** [comment]
Did you see this one? https://github.com/GetStream/stream-laravel#notification-feed
In order to send activities to a notification feed you have to implement the activityNotify method in your activity class. The method returns the notification feeds where the activity must be stored.

**Comment by MoZart182** [comment]
Ooh thx! Now I understand. Thanks for your help.

**Comment by tbarbugli** [comment]
glad it helped :)
