### ISSUE TITLE
GuzzleHttp error

### ISSUE THREAD

**Issue by nicgutierrez** [GetStream/stream-laravel#19]
Hi.

I'm getting the following error:
Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /vagrant/quantofa/vendor/guzzlehttp/guzzle/src/Client.php on line 88 and defined

While trying to follow feeds or getActivities.
I'm using Laravel 5.

Thanks

**Comment by nicgutierrez** [comment]
ok.. I think the problem here is that Laravel 5 uses a version of Guzzle that is not supported by GetStream?

https://github.com/guzzle/guzzle/issues/1123

**Comment by tbarbugli** [comment]
afaik Laravel does not require Guzzle. what version of stream-laravel are you using?

**Comment by nicgutierrez** [comment]
I see.

I'm currently using ~2.1

**Comment by tbarbugli** [comment]
I suggest you to update to 2.2.3

**Comment by nicgutierrez** [comment]
No luck. I'm still getting the same error..
I just started using it and I'm doing a pretty simple test:

    $comonte = FeedManager::getFeed( 'team', 'comonte' );
    $nic = FeedManager::getFeed( 'user', 'nic' );
    $nic->followFeed( 'team', 'comonte' );

(I created the "team" slug).

**Comment by tbarbugli** [comment]
what version of Guzzle do you have installed? make sure you have >=4.0 <6.0
installed.

**Comment by nicgutierrez** [comment]
My composer.json file doesn't include "Guzzle", and the version that is being installed is:

guzzlehttp/guzzle : 6.0.1
guzzle/guzzle: 3.9.3

**Comment by tbarbugli** [comment]
ok guzzle 6.0.1 is the issue here. something like this should make sure
composer installs the right version of guzzle
something like this should fix it
```
composer remove guzzlehttp/guzzle
composer remove get-stream/stream-laravel
composer remove get-stream/stream
composer install
```

**Comment by nicgutierrez** [comment]
Thanks for that @tbarbugli.
I managed to fix it by manually including Guzzle in my composer file as follows

    "get-stream/stream-laravel": "2.2.3",
    "guzzlehttp/guzzle": "<6.0"

Cheers.
Nic

**Comment by Grusglo** [comment]
Hi

Having issues with this, I cannot use the suggested solution since I already have another package which requires `"guzzlehttp/guzzle": "~6.0"`. Any chance there is an update inbound for this package?

Best regards

**Comment by tbarbugli** [comment]
working on this!

**Comment by tbarbugli** [comment]
@Grusglo stream-laravel on master is now on guzzle 6

**Comment by Grusglo** [comment]
Thank you for the prompt update! Really appreciate it. @tbarbugli
