### ISSUE TITLE
 The stored feed has wrong attributes (Laravel 5.1)

### ISSUE THREAD

**Issue by hootlex** [GetStream/stream-laravel#20]
##### Example scenario:

Quiz model uses GetStream\StreamLaravel\Eloquent\ActivityTrait.
When a new Quiz is created the stored feed has the following attributes:
- "actor": "App\User:3"
- "foreign_id": "App\Quiz:394"
- "id": "*****"
- "object": "App\Quiz:394"
- "origin": null
- "target": null
- "time": "2015-09-25T02:42:23.000000"
- "to": []
- "verb": "app\quiz"
##### Expected behaviour:

 The stored feed has the following attributes:
- "actor": "App\User:3"
- "foreign_id": "394"
- "id": "*****"
- "object": "App\Quiz"
- "origin": null
- "target": null
- "time": "2015-09-25T02:42:23.000000"
- "to": []
- "verb": "created"

The most important attribute is "verb" and I assume it had to be correct for specific actions like create, update, delete.

**Comment by tbarbugli** [comment]
https://github.com/GetStream/stream-laravel#customize-activity-verb

**Comment by kyrenator** [comment]
I know that the verb can be changed manually, the point is to change through the trait.
The foreign_id field is also wrong.
