### ISSUE TITLE
Call to a member function getKey() on null. Issue

### ISSUE THREAD

**Issue by hoangnhiho** [GetStream/stream-laravel#21]
Hey i'm fairly new so I'd like to apologies for the noob question/error.
So i'm getting the following error. I was wondering if anyone could point me in the right direction

PHP  42. App\Models\User->activityActor() /home/vagrant/Bold/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/Eloquent/ActivityTrait.php:109
PHP  43. GetStream\StreamLaravel\Eloquent\Utils::createModelReference() /home/vagrant/Bold/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/Eloquent/ActivityTrait.php:54
                                                    
[Symfony\Component\Debug\Exception\FatalErrorException]  
Call to a member function getKey() on null

**Comment by tbarbugli** [comment]
How do your models look like? Can you share them here or on gist?

**Comment by hoangnhiho** [comment]
Thanks for the quick reply. I've emailed you the details.

**Comment by hoangnhiho** [comment]
Issue fixed
