### ISSUE TITLE
[Question] what's the purpose of this Facade FeedManager?

### ISSUE THREAD

**Issue by simkimsia** [GetStream/stream-laravel#22]
inside the CreateRemoveObserver.php

we have  $manager = \App::make('feed_manager');

at https://github.com/GetStream/stream-laravel/blob/master/src/GetStream/StreamLaravel/Eloquent/CreateRemoveObserver.php#L7

What's the purpose of this FeedManager? 

I am trying to port this to CakePHP 3.x so I am trying to understand this.

**Comment by tbarbugli** [comment]
the FeedManager exposes many helper functions (see https://github.com/GetStream/stream-laravel/blob/master/src/GetStream/StreamLaravel/StreamLaravelManager.php) that makes the integration between stream and framework simpler. For instance, when you perform `followUser` the manager looks up what is the name of the feed group for user feeds ('user' by default) and what are the names of the newsfeeds ('flat' and 'aggregated' by default) and creates a follow relationships between these feeds.

The FeedManager is also responsible of handling the two activityCreated/activityDeleted callback functions (when one activity model is deleted or added it performs an API call to Stream)

**Comment by simkimsia** [comment]
Thank you for answer. 

Why not just instantiate the StreamLaravelManager class then?

**Comment by tbarbugli** [comment]
using Facedes is a very common idiom in Laravel. Using a Singleton would work as well too

**Comment by simkimsia** [comment]
Understood. Thank you.
