### ISSUE TITLE
Use jobs/queue for publishing to Stream

### ISSUE THREAD

**Issue by dwightwatson** [GetStream/stream-laravel#34]
Having a quick look over the code it doesn't look like you're using the app's queue in order to publish events to Stream. This means whenever a relevant model is created/updated/deleted the HTTP request to publish that to Stream is going to happen inline and slow down the request.

Are there any plans to support jobs/queue for this sort of publishing, or are you open to pull requests that would make this change?

**Comment by tbarbugli** [comment]
sounds like a very good improvement indeed. I am definetely open to PRs on this!

**Comment by andersfloor** [comment]
I'd like this, as long you could indicate this (or maybe override a general config setting) per request. There can be situations where you wish to immediately return an updated timeline to the user in the response.
