### ISSUE TITLE
Using ActivityTrait on a model that isn't a user

### ISSUE THREAD

**Issue by xKairu** [GetStream/stream-laravel#36]
So I have a User model, which represents a user, unsurprisingly.

A user can befriend another user and view their feeds, that works fine. My issue is that I also have a Team model that a user can follow. This is how I make the activity for it a 'hosted event' that is bound to a Team.

```
$instance = app(CommunityHostedRepository::class)->create([
    'team_id' => $event->eventable_id,
    'event_id' => $event->id,
]);
```

The core issue here is that the activity in Stream gets pushed to the `user:1` origin, so it only shows in the feeds for friends of user1, but not user2, who follows team1 and is not a friend of user1.

I went and removed the trait from my CommunityHosted model, and added the following:

```
$feed = FeedManager::getFeed('team', $event->eventable_id);
$feed->addActivity([
    "actor" => Utils::createModelReference($instance->team),
    "verb" => $instance->activityVerb(),
    "object" => Utils::createModelReference($instance),
]);
```

And this works fine. It gets pushed to the `team:1` origin and comes up on both user1 & user2's feeds. The `foreign_id` isn't set, but I can still access the Eloquent model through `$activity['object']` just fine.

My CommunityHosted model looks like so:

```
class CommunityHosted extends Model implements Transformable
{
    use TransformableTrait, ActivityTrait;

    protected $table = 'activity_communityhosted';

    protected $fillable = [
        'team_id',
        'event_id',
    ];

    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    public function event()
    {
        return $this->belongsTo(Event::class);
    }

    public function activityVerb()
    {
        return 'communityevent';
    }

    public function activityLazyLoading()
    {
        return ['team', 'event'];
    }

    public function activityActorMethodName()
    {
        return 'team';
    }
}
```

So I have the actor set properly, it's just that it's setting the origin to essentially,

```
'user:' . Auth::user()->id
```

rather than, 
```
$instance->activityActorMethodName() . ':' . $instance->id
```

Or am I completely missing the mark here and not setting something that I should be?

**Comment by tbarbugli** [comment]
My suggestion is to go back to your first approach where activities are added to `user:1` and to use the `to` target field to copy the same activity to the `team:1` feed. This way you add the activity only once and it added directly to the origin feed `user:1`, copied to `team:1` and then propagated to all `team:1` followers.

You can use the `to` target field by implementing the `activityNotify` method (you can find examples on the main README).

**Comment by xKairu** [comment]
Would that not then duplicate the activity to unrelated users?

`user:1` is friends with `user:2`
`user:3` is friends with `user:1` but does not follow `team:1`

`user:1` makes the activity on behalf of `team:1` as an admin, then the activity will show for `user:3` when they don't follow `team:1`.

**Comment by tbarbugli** [comment]
Did you confirm that `activityActorMethodName` from `CommunityHosted` is called when the activity is created?

**Comment by xKairu** [comment]
```
public function activityActorMethodName()
{
    \Log::info('activityActorMethodName called');
    return 'team';
}
```

When `tail`'ing the logs:
```
[2016-11-05 00:31:44] local.INFO: activityActorMethodName called
[2016-11-05 00:31:44] local.INFO: activityActorMethodName called
```
