### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by xKairu** [GetStream/stream-laravel#42]
`App::share()` has been removed in 5.4 and replaced with `App::singleton()`.

Just changing `app->share` to `app->singleton` then results in

```
[ErrorException]
Illegal offset type in unset
```

Which is resolved by removing the service provider from my app config.

**Comment by BirdyUK** [comment]
@xKairu can you explain a little more how you fixed the issue please? Im facing the issue having installed this package.

Thanks

**Comment by xKairu** [comment]
@BirdyUK You'll need to use dev-master as a tag for the latest fix hasn't been made.

**Comment by tbarbugli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Laravel 5.4](https://trello.com/c/GDJFX2xx/1-support-laravel-5-4)
