### ISSUE TITLE
Laravel 5.4 issue

### ISSUE THREAD

**Issue by BirdyUK** [GetStream/stream-laravel#44]
Hi, when installing this package with laravel 5.4, The install goes well and no issues are shown untill you try to use laravel or artisan.

You then get this message:
`
FatalThrowableError in StreamLaravelServiceProvider.php line 45: Call to undefined method Illuminate\Foundation\Application::share()`

Since following #43 and #42  i am getting the following error:
```
StreamFeedException in Feed.php line 102: {"code": 6, "detail": "The following feeds are not configured: 'user'. \nThis could be the cause of a typo, but otherwise you should configure them on the dashboard of this app.", "duration": "4ms", "exception": "FeedConfigException", "status_code": 400}
```

Any ideas what the best solution is?

**Comment by BirdyUK** [comment]
Ok so ive kind of fixed the issue at hand, The problem was i did not have a 'user' feed group and when i added a feed group called user i then got this problem:

`StreamFeedException in Feed.php line 102: {"code": 4, "detail": "Errors for fields 'verb'", "duration": "7ms", "exception": "InputException", "exception_fields": {"verb": ["Ensure this value has at most 20 characters (it has 21)."]}, "status_code": 400}`

to overcome this issue i needed to add a function to the model like 

```
    public function activityActorMethodName()
    {
        return 'author';
    }
```

Once i added this to the model the activity was logged to the Stream like so:

`id
actor
verb
object
foreign_id
time
to
 
d5117880-f0ce-11e6-8080-80010ea35f01
App\User:43
created
App\Models\Tasks\Task:33
App\Models\Tasks\Task:33
2017-02-12T02:56:21.000000
[]`


Hopefully someone with some more experience can produce a more details laravel 5.4 tutorial / explanation to help the less experienced folk.

Thanks.

**Comment by tbarbugli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Laravel 5.4](https://trello.com/c/GDJFX2xx/1-support-laravel-5-4)

**Comment by tbarbugli** [comment]
Laravel 5.4 is supported on last release
