### ISSUE TITLE
support for laravel 5.4

### ISSUE THREAD

**Issue by xcaptain** [GetStream/stream-laravel#45]
In my newly installed laravel 5.4 application, running `php artisan vendor:publish --provider="GetStream\StreamLaravel\StreamLaravelServiceProvider"` gets 
> [Symfony\Component\Debug\Exception\FatalThrowableError]
> Call to undefined method Illuminate\Foundation\Application::share()

https://laravel.com/docs/5.4/upgrade
> share Method Removed

**Comment by xcaptain** [comment]
sorry for my careless, this issue has beed fixed in the master branch.
in composer.json use `"get-stream/stream-laravel": "dev-master",` solves this.

And please add a new tag for current master branch because v2.2.6 doesn't work in laravel5.4, thanks.

**Comment by tbarbugli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Laravel 5.4](https://trello.com/c/GDJFX2xx/1-support-laravel-5-4)

**Comment by tbarbugli** [comment]
Released a new version with Laravel 5.4
