### ISSUE TITLE
addActivity() undefined method

### ISSUE THREAD

**Issue by ArneAnka** [GetStream/stream-laravel#49]
Hi!

Im using stream-laravel 2.2 for larval 5.4 and I keep getting:

```
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method GetStream\StreamLaravel\StreamLaravelManager::addActivity() in /Users/homeboi/code/tree/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
```

According to docs https://getstream.io/docs/php/#adding-activities, this is the workflow?

```php
        $data = [
            'actor' => Auth::user()->id,
            'verb' => 'favourited',
            'object' => 'user',
        ];
        \FeedManager::addActivity($data);
```

**Comment by tbarbugli** [comment]
Models are added to feeds when saved (and removed when deleted) automatically. If you want to add activities manually you need to use the API client (which you can retrieve from the Feedmanager).

```php
FeedManager::getClient->addActivity($data);
```

**Comment by ArneAnka** [comment]
The error persist. This is the whole function

```
    public function favouriteGame(Game $game)
    {
        Auth::user()->favourites()->attach($game->slug);

        $data = [
            'actor' => Auth::user()->id,
            'verb' => 'favourited',
            'object' => 'user',
        ];
        \FeedManager::getClient()->addActivity($data);
        
        return back()->with('success', 'You favorited game '. $game->title);
    }
```

It now throws error `Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method GetStream\Stream\Client::addActivity()`

**Comment by hannesvdvreken** [comment]
> Im using stream-laravel 2.2 for __larval__ 5.4 and I keep getting:

You might have mistyped something there. Did you mean you're using the __Larvel__ 🐛  framework?

https://github.com/fideloper/larvel

😂 

All jokes aside...

What I think you want to do here is to add a Activity to a user's feed. For that you need to get the user's feed with

```
$feed = FeedManager::getUserFeed(Auth::user()->id);
```

From this point on, you can start adding activities to that feed.

```
$feed->addActivity($data);
```

Does this make sense to you?

I'm closing this issue for now. In case your issue isn't resolved yet, just tell me and I will reopen it and continue to help get it resolved.
