### ISSUE TITLE
Possible Bug in Enrichment

### ISSUE THREAD

**Issue by jaredloman** [GetStream/stream-laravel#51]
When attempting to enrich data as per the directions in the documentation I would always receive back an array of empty objects. After spending the better part of the day trying to figure out the discrepancy between what I was doing and what was going on in the examples and documentation I finally decided to explore the code a bit.

It seems that the issue resides on 66 of Enrich.php where the function attempts to establish each array item as an instance of EnrichedActivity. I'm far from a PHP expert... in fact, I couldn't easily write these classes my self...so I could be entirely off on this but since none of the class methods are used you just end up with an empty object. Anyhow... I have temporarily fixed this just by commenting out Line 95 and bypassing this function but it would be great to figure out a more official solution.

**Comment by tbarbugli** [comment]
can you pprint the data before is converted into a list of EnrichedActivity objects?

**Comment by jaredloman** [comment]
Here is an example of the data that is passed into wrapActivities function, converted to JSON for readability. 
`[
	{
		"actor": "App\\Volunteer:2",
		"foreign_id": "App\\Post:76",
		"id": "81392400-41d3-11e7-8080-80014b644813",
		"object": "App\\Post:76",
		"origin": "user:2",
		"target": null,
		"time": "2017-05-26T05:23:52.000000",
		"to": [

		],
		"verb": "post"
	},
	{
		"actor": "App\\Volunteer:4",
		"foreign_id": "App\\Post:75",
		"id": "6d8dbd80-41d3-11e7-8080-800072dc67ae",
		"object": "App\\Post:75",
		"origin": "user:4",
		"target": null,
		"time": "2017-05-26T05:23:19.000000",
		"to": [

		],
		"verb": "post"
	},
	{
		"actor": "App\\Volunteer:3",
		"foreign_id": "App\\Post:74",
		"id": "54850c80-41d3-11e7-8080-8000150b1cda",
		"object": "App\\Post:74",
		"origin": "user:3",
		"target": null,
		"time": "2017-05-26T05:22:37.000000",
		"to": [

		],
		"verb": "post"
	},
	{
		"actor": "App\\Volunteer:112",
		"foreign_id": "App\\Post:73",
		"id": "420ad300-41d3-11e7-8080-800064af7a34",
		"object": "App\\Post:73",
		"origin": "user:112",
		"target": null,
		"time": "2017-05-26T05:22:06.000000",
		"to": [

		],
		"verb": "post"
	},
	{
		"actor": "App\\Volunteer:1",
		"foreign_id": "App\\Post:72",
		"id": "27385e80-41d3-11e7-8080-800066a283c2",
		"object": "App\\Post:72",
		"origin": "user:1",
		"target": null,
		"time": "2017-05-26T05:21:21.000000",
		"to": [

		],
		"verb": "post"
	}
]`

and here is a var dump:

`array(5) { [0]=> array(9) { ["actor"]=> string(15) "App\Volunteer:2" ["foreign_id"]=> string(11) "App\Post:76" ["id"]=> string(36) "81392400-41d3-11e7-8080-80014b644813" ["object"]=> string(11) "App\Post:76" ["origin"]=> string(6) "user:2" ["target"]=> NULL ["time"]=> string(26) "2017-05-26T05:23:52.000000" ["to"]=> array(0) { } ["verb"]=> string(4) "post" } [1]=> array(9) { ["actor"]=> string(15) "App\Volunteer:4" ["foreign_id"]=> string(11) "App\Post:75" ["id"]=> string(36) "6d8dbd80-41d3-11e7-8080-800072dc67ae" ["object"]=> string(11) "App\Post:75" ["origin"]=> string(6) "user:4" ["target"]=> NULL ["time"]=> string(26) "2017-05-26T05:23:19.000000" ["to"]=> array(0) { } ["verb"]=> string(4) "post" } [2]=> array(9) { ["actor"]=> string(15) "App\Volunteer:3" ["foreign_id"]=> string(11) "App\Post:74" ["id"]=> string(36) "54850c80-41d3-11e7-8080-8000150b1cda" ["object"]=> string(11) "App\Post:74" ["origin"]=> string(6) "user:3" ["target"]=> NULL ["time"]=> string(26) "2017-05-26T05:22:37.000000" ["to"]=> array(0) { } ["verb"]=> string(4) "post" } [3]=> array(9) { ["actor"]=> string(17) "App\Volunteer:112" ["foreign_id"]=> string(11) "App\Post:73" ["id"]=> string(36) "420ad300-41d3-11e7-8080-800064af7a34" ["object"]=> string(11) "App\Post:73" ["origin"]=> string(8) "user:112" ["target"]=> NULL ["time"]=> string(26) "2017-05-26T05:22:06.000000" ["to"]=> array(0) { } ["verb"]=> string(4) "post" } [4]=> array(9) { ["actor"]=> string(15) "App\Volunteer:1" ["foreign_id"]=> string(11) "App\Post:72" ["id"]=> string(36) "27385e80-41d3-11e7-8080-800066a283c2" ["object"]=> string(11) "App\Post:72" ["origin"]=> string(6) "user:1" ["target"]=> NULL ["time"]=> string(26) "2017-05-26T05:21:21.000000" ["to"]=> array(0) { } ["verb"]=> string(4) "post" } }`

**Comment by dwightgunning** [comment]
Hi Jared,

How are you iterating and/or accessing the activities after enrichment?

I have tested successfully with the following trace logging added to `TaskController.php`:

```
    public function index(Request $request)
    {

        // Get your timeline:
        $feed = \FeedManager::getNewsFeeds($request->user()->id)['timeline'];

        // Get your timeline activities from Stream:
        $enricher = new Enrich(array('actor', 'object'));
        $activities = $feed->getActivities(0,25)['results'];
        Log::error(sizeof($activities));
        $activities = $enricher->enrichActivities($activities);

        Log::error("After enrichment");
        foreach ($activities as $act) {
            Log::error($act["name"]);
        }

        return view('tasks.index', [
            'tasks' => $this->tasks->forUser($request->user()),
            'activities' => $activities
        ]);
    }
```

Note that the EnrichedActivity class doesn't implement JsonSerializable interface, so you can't simply emit a json serialized string (we should improve this part of the integration).

**Comment by jaredloman** [comment]
Hey Dwight,

Thanks for reaching out. It's possible that the issue was as simple as missing passing the array into the Enrich object. Using the documentation as a reference it suggests setting up the enrichment as follows:

`use GetStream\StreamLaravel\Enrich;
$enricher = new Enrich();
$activities = $feed->getActivities(0,25)['results'];
$activities = $enricher->enrichActivities($activities);`

I suppose I should have posted an example of my code with this report but didn't consider it since I was copying the documentation example verbatim. 

I'll do some testing with the additional array specifying what needs to be enriched and see if that brings this to a close. In the mean time, it would be great to see an update to the documentation assuming that this is in-fact the issue I was having just to ensure that others aren't pulling out all their hair like I was. :)

**Comment by dwightgunning** [comment]
Thanks again for the contribution here @jaredloman - I'll close this issue off since it looks to be resolved.
