### ISSUE TITLE
Notification activity not removed on Deletion.

### ISSUE THREAD

**Issue by imonoid** [GetStream/stream-laravel#55]
Guys, I have an issue with Notification feeds not being removed on deletion.
The activity feed is removed but the notification feed entry is retained.
Seems to happen on some model only.  I be using:
"get-stream/stream": "^2.3",
 "get-stream/stream-laravel": "~2.2.6",

This is the sample screenshot:
![01](https://user-images.githubusercontent.com/20701396/31065376-b7c34db0-a755-11e7-9eca-8d22adc4e024.PNG)

User 1 Feed:
![02](https://user-images.githubusercontent.com/20701396/31065265-f7063f10-a754-11e7-8072-d3f9925b4872.PNG)

User 1 Feed (After delete):
![02afterdelete](https://user-images.githubusercontent.com/20701396/31065268-f707b192-a754-11e7-9823-29f23faa7c95.PNG)

User 1 Notification:
![03](https://user-images.githubusercontent.com/20701396/31065269-f707f17a-a754-11e7-92af-e38b99bff7ad.PNG)

User 1 Notification Feed (After delete):
![03afterdelete](https://user-images.githubusercontent.com/20701396/31065266-f7071656-a754-11e7-99b3-aedfd393a3be.PNG)

User 2 Feed:
![04](https://user-images.githubusercontent.com/20701396/31065267-f7079acc-a754-11e7-8147-b2aeed6d61e3.PNG)

User 2 Feed (After delete):
![04afterdelete](https://user-images.githubusercontent.com/20701396/31065270-f708064c-a754-11e7-9c38-15c1cf369670.PNG)

User 2 Notification:
![05](https://user-images.githubusercontent.com/20701396/31065271-f72a493c-a754-11e7-9336-b8cff674a5fd.PNG)

User 2 Notification Feed (After delete):
![05afterdelete](https://user-images.githubusercontent.com/20701396/31065272-f72aadaa-a754-11e7-8bdb-fd42f13ae244.PNG)

This is the sample code:

    public function eventPostDelete($conversationId, Request $request) {
      
      $success = false;
      $errors = [];

      $conversation = EventConversation::find($conversationId);

      if (!empty($conversation) && $conversation->author_id == Auth::user()->id) {
        
        $evtcl = EventConversationLike::where("event_conversation_id", $conversationId)->get();
        foreach ($evtcl as $i):
          $i->delete();
        endforeach;

        $evtcm = EventConversationMention::where("event_conversation_id", $conversationId)->get();
        foreach ($evtcm as $i):
          $i->delete();
        endforeach;

        $ecrs = EventConversationReply::where("event_conversation_id", $conversationId)->orWhere("conversation_replies_parent_id", $conversationId)->get();
        foreach($ecrs as $ecr) {

          $evtcrl = EventConversationReplyLike::where("event_conversation_reply_id", $ecr->id)->get();
          foreach ($evtcrl as $i):
            $i->delete();
          endforeach;

          $evtcrm = EventConversationReplyMention::where("event_conversation_reply_id", $ecr->id)->get();
          foreach ($evtcrm as $i):
            $i->delete();
          endforeach;

          $ecr->delete();
        }
        
        $conversation->delete();
        
        $success = true;

      } else {
        $errors[] = "Conversation not found.";
      }

      return response()->json([
        'success' => $success,
        'conversation' => $conversation,
        'errors' => $errors
      ]);
    }

**Comment by dwightgunning** [comment]
@hannesvdvreken could you please take a look at this?

**Comment by hannesvdvreken** [comment]
Hi Raymund,

I'm not 100% sure what your application domain model is, which of the Models `EventConversation`, `EventConversationLike`, `EventConversationMention`, `EventConversationReply`, `EventConversationReplyLike` or `EventConversationReplyMention` is having `to` fields defined to create notifications in the first place, and which notifications should be removed and are, according to you, not being removed?

I hope I can help you solve this with you,
Cheers.

**Comment by imonoid** [comment]
Hi Hannes,

EventConversationReply and EventConversationReplyLike are the ones that have "to fields".
The conversation reply to field is pointed to user of EventConversation being replied to.
The reply like to field is pointed to user of EventConversationReply being liked.

EventConversationReply 

	<?php
	namespace App;

	use Auth;
	use GetStream\StreamLaravel\Facades\FeedManager;
	use Illuminate\Database\Eloquent\Model;

	class EventConversationReply extends Model
	{
	  use \GetStream\StreamLaravel\Eloquent\ActivityTrait;
	  
	  public function postOwner()
	  {
		  return $this->belongsTo('App\EventConversation', 'event_conversation_id', 'id');
	  }

	  public function poster()
	  {
		  return $this->hasOne('App\User', 'id', 'user_id');
	  }
	  
	  public function replyer()
	  {
		  return $this->belongsTo('App\User', 'user_id', 'id');
	  }
	  
	  public function fakePoster()
	  {
		  return $this->hasOne('App\FakeUser', 'id', 'user_id');
	  }

	  public function childComments()
	  {
		  return $this->hasMany('App\EventConversationReply', 'conversation_replies_parent_id', 'id')->orderBy('created_at', 'desc');
	  }

	  public function postCommentLikes()
	  {
		  return $this->hasMany('App\EventConversationReplyLike', 'event_conversation_reply_id', 'id');
	  }

	  public function likedByUser()
	  {
		return $this->postCommentLikes()->where('user_id', Auth::user()->id);
	  }

	  public function activityVerb()
	  {
		  return 'evt_conv_reply';
	  }

	  public function activityActorMethodName()
	  {
		  return 'replyer';
	  }

	  public function activityNotify()
	  {
		if (!empty($this->postOwner->user->id) && $this->postOwner->user->id == Auth::user()->id) {
		  return array();
		}
		$targetFeed = FeedManager::getNotificationFeed($this->postOwner->user->id);
		return array($targetFeed);
	  }
	}

EventConversationReplyLike 

	<?php
	namespace App;

	use GetStream\StreamLaravel\Facades\FeedManager;
	use Illuminate\Database\Eloquent\Model;

	class EventConversationReplyLike extends Model
	{
	  use \GetStream\StreamLaravel\Eloquent\ActivityTrait;
	  
	  public function conversationReply()
	  {
		  return $this->belongsTo('App\EventConversationReply', 'event_conversation_reply_id', 'id');
	  }
	  
	  public function liker()
	  {
		  return $this->belongsTo('App\User', 'user_id', 'id');
	  }
	  
	  public function liker2()
	  {
		  return $this->hasOne('App\User', 'id', 'user_id');
	  }

	  public function activityVerb()
	  {
		  return 'evt_conv_reply_like';
	  }

	  public function activityActorMethodName()
	  {
		  return 'liker';
	  }

	  public function activityNotify()
	  {
		$targetFeed = FeedManager::getNotificationFeed($this->conversationReply->user_id);
		return array($targetFeed);
	  }
	}

**Comment by hannesvdvreken** [comment]
Looks correct to me, at first sight.

I can't really tell what's the problem, but I can tell you that if notifications are being pushed with `activityNotify`, they will get removed again when you remove the model, by using this Activity.

If you can pinpoint a flaw in our library, I'd be happy to help you resolve the issue, but at this moment I can't dig into your code base to find the real problem.

**Comment by imonoid** [comment]
I understand Hannes.  I also cannot pinpoint what the issue is.  I have encountered this issue before but I thought it had gone away.  Encountered it again, just when we are about to go live with our app.

Anyway, I'll try to double delete activities manually using the Stream-php method, just to ensure.

**Comment by hannesvdvreken** [comment]
Good luck figuring it out, and good luck with the launch of your app!
