### ISSUE TITLE
Mass deletion question.

### ISSUE THREAD

**Issue by imonoid** [GetStream/stream-laravel#57]
guys, what is the correct way of doing mass deletion?

i have a Post object that I want to delete, that has:
PostComments
PostMentions
PostLikes
PostReply
PostReplyMention
PostReplyLike

assuming each of these records can reach more or less a thousand records,  should i manually iterate over them?
as I have noticed **PostLikes::where("liker_id", Auth::id())->delete();** does not seem to work.

**Comment by hannesvdvreken** [comment]
Hi.

One strategy could be to soft delete, and when a user clicks on a notification for a Post that has been deleted: just show users a page that says: no post found. From a UX point of view this could be perfectly fine. Any link to the post will be broken anyway.

Another strategy is to delete activities in Stream in a background job, but (as you said: thousands of records) it's not an easy thing to do at scale. We don't have a way to batch delete activities in one API call, at the moment. So: rate limits are to be respected. Rate limits go up if you upgrade to a higher plan.

By the way: if you wish, you can also send questions like these to stackoverflow in the future using the [getstream-io tag](https://stackoverflow.com/questions/tagged/getstream-io). Other Stream users can share you their experience too.

Cheers

**Comment by hannesvdvreken** [comment]
> guys,

What if... I was a  👩 replying to you? 😃  I wouldn't feel very addressed.
