### ISSUE TITLE
GetStream - Company posts no longer showing in feed after switching to Aggregated Timeline

### ISSUE THREAD

**Issue by imonoid** [GetStream/stream-laravel#61]
I have posted this issue on Stackoverflow, but would like to know your input about it as well, as I am not sure if this is a bug, or just some misconfiguration on my part.  My issue is that posts coming from my Company feed does'nt seem to show up on the aggregated timeline, though it shows up perfectly on the non-aggregated.

[this is the link to the stackoverflow question also](https://stackoverflow.com/questions/47138294/getstream-company-posts-no-longer-showing-in-feed-after-switching-to-aggregate)

**Comment by imonoid** [comment]
this is working now.  solution was to follow the company with your aggregated timeline, not just the regular timeline.

**Comment by hannesvdvreken** [comment]
🙂
