### ISSUE TITLE
ActivityTrait doesn't boot

### ISSUE THREAD

**Issue by xKairu** [GetStream/stream-laravel#62]
Laravel 5.4.28, stream-laravel 2.2.8, stream-php 2.5.0.

A while ago my activity feeds stopped working and they kind of just got forgotten about. I'm coming back to it, and I've found:

- My eloquent models are being created just fine, it's just not getting pushed to getstream.
- Placed a log statement into ActivityTrait@bootActivityTrait to see if the trait is even being triggered.
- The repository library I'm using, doesn't call `Model::create()`, it calls `Model::newInstance()`. I've tried directly calling `MyModel::create()` to see if the trait gets triggered, but it doesn't.

I've tried making a new app within get-stream, no success. If I manually push the activity within my model boot function, it works:

```
public static function boot()
{
    static::created(function ($model) {
        $manager = \App::make('feed_manager');
        $manager->activityCreated($model);
    });
}
```

This is an *okay* workaround for me personally, as I only have a handful of activity actions, but I really wouldn't want to do this if my models were any more complicated than a bridge between a user and an object. This also works when using `Model::newInstance()`, so I can only assume the issue lies within the trait not booting properly.

**Comment by hannesvdvreken** [comment]
Hi!

I suspect you updated your installation of this package from 2.2.3 or earlier to 2.2.4 or later.

In 2.2.4 a breaking change was introduced, where you now have to do this in every activity model:

```php
public static function boot()
{
    static::bootActivityTrait();
}
```

or simpler:

```php
use ActivityTrait { bootActivityTrait as boot; }

// As opposed to previously:
use ActivityTrait;
```

See: https://github.com/GetStream/stream-laravel/compare/2.2.3...2.2.4#diff-e18ab2380fd8201ce8c6beaa50e03178L130

I'm truly sorry about this, under my watch this will never happen again ;-)
