### ISSUE TITLE
Enrichment Object Empty

### ISSUE THREAD

**Issue by zagreusinoz** [GetStream/stream-laravel#68]
Hi there

When trying to enrich my activities I get an empty object. 

Here is the code in my controller:
```php
$enricher = new Enrich;
$feed = FeedManager::getUserFeed($request->user()->id);
$activities = $feed->getActivities()['results'];
Log::debug('activity', [$activities]);
$activities = $enricher->enrichActivities($activities);
Log::error('enriched', [$activities]);
```

This is what I get in the log:
```
[2018-03-18 12:26:15] local.DEBUG: activity [[{"actor":"App\\Models\\User:1","foreign_id":"App\\Models\\Measurement:16","id":"19c0cd80-2aa0-11e8-8080-80003305d0b1","object":"App\\Models\\Measurement:16","origin":null,"target":"","time":"2018-03-18T11:32:55.000000","verb":"measurement"}]] 
[2018-03-18 12:26:15] local.ERROR: enriched [["[object] (GetStream\\StreamLaravel\\EnrichedActivity: {})"]] 
```

Note, I saw #51 and tried the solution suggested and have tried all of the following ways of calling Enrich ```$enricher = new Enrich```, ```$enricher = new Enrich()``` and ```$enricher = new Enrich(['actor', 'object])```but none of the solves it for me.

I'm using Laravel 5.5.39 and 2.3.0 of this package.

Thanks in advance.

**Comment by tbarbugli** [comment]
This can happen if some of the data referenced in the activity was deleted from your database. I see you have a few refs in there (eg. App\\Models\\Measurement:16). My suggestion is to verify they all are present in your database.

**Comment by zagreusinoz** [comment]
Ok thanks.  I fixed that.  Thanks for the suggestion.
