### ISSUE TITLE
Any way to conditionally add models to feeds

### ISSUE THREAD

**Issue by peterholcomb** [GetStream/stream-laravel#69]
We have a situation where we would only want to add a model to a feed based on if the model has a certain property or not.  For example, I want to create a new blog post and mark it as either private or public.  I only want that model to be added to my feed if I mark it as public.

Is that possible with this library?

**Comment by hannesvdvreken** [comment]
The easiest way would be to create your own version of the [`CreateRemoveObserver`](https://github.com/GetStream/stream-laravel/blob/master/src/GetStream/StreamLaravel/Eloquent/CreateRemoveObserver.php#L7). In there, check if it's private or public, and call the Manager accordingly.

You can use your own CreateRemoveObserver by changing the static [`activitySyncPolicy`](https://github.com/GetStream/stream-laravel/blob/master/src/GetStream/StreamLaravel/Eloquent/ActivityTrait.php#L10) variable of your model.
