### ISSUE TITLE
The blade template in this repository causes logs to be shown to user

### ISSUE THREAD

**Issue by ow** [GetStream/stream-laravel#76]
There's a problem with the blade template for rendering activities after enriching them: https://github.com/GetStream/stream-laravel/blob/5870fb272fa2aa0b9c1f7f893a044ceb39d588f1/src/views/render_activity.blade.php

This file, if you're enriching fewer activities than you tried to get (I retrieved 10, but only had four), causes this to be output to the screen: 

`    Log::warning('The activity could not be rendered, the following field/refs could not be enriched:', $activity->getNotEnrichedData());`

I _think_ that this needs to be escaped like `\log::warning` or done a different way -- this got out into production for me and it was a bit embarrassing, as it's pretty difficult to prevent as well. If there were a method for checking unenriched entities...

**Comment by ow** [comment]
In case anyone stumbles on this, obviously the GetStream folks aren't interested in helping so you can use my own fork, which actually removes the error/suppresses it from being shown to your users. https://github.com/ow/stream-laravel

**Comment by tbarbugli** [comment]
@ow sorry, we missed this issue on Github, we are always happy to help :)

AFAIK the best solution here is to change your Laravel configuration to not write log messages to stdout when running on a production environment and to do that on your dev environment.

The relevant docs are available here: https://laravel.com/docs/5.8/logging#introduction

**Comment by ow** [comment]
@tbarbugli All good—but that's not the case. You can't use `Log::info` in a blade file, so it just blobs it out into HTML. I didn't see this until 100-200 of my users were complaining about it in production, which was because it was unable to enrich a scoped post.

The best way to deal with this would be to stop including `Log::warning('The activity could not be rendered, the following field/refs could not be enriched:', $activity->getNotEnrichedData());` in your blade template, because you can't run that Blade-side. That's all I removed in my fork. :)

**Comment by tbarbugli** [comment]
that's strange :) is `Log` in that scope something else than Laravel's `Log` facade?

**Comment by ow** [comment]
No, it's just that you [cannot log from a Blade template with the built-in logger](https://stackoverflow.com/questions/52609466/can-i-log-from-a-laravel-blade-template), which is what you're trying to do here: https://github.com/GetStream/stream-laravel/blob/5870fb272fa2aa0b9c1f7f893a044ceb39d588f1/src/views/render_activity.blade.php
