### ISSUE TITLE
User reference

### ISSUE THREAD

**Issue by azurinspire** [GetStream/stream-laravel#77]
If I add user and data with FleetManager like this:
```php
$client = FeedManager::getClient();
$client->users()->add(strval($user->id), ['name' => $user->name]);
```
data is added as internal stream user which is referenced by SU:(user-id)

But as ActivityTrait is using model reference App\User:(user-id) the activity actor is not automatically enriched like it would if it uses the internal reference format.

Is it somehow possible to control the format what ActivityTrait is using?

**Comment by tbarbugli** [comment]
Good question.

You can customize how each field is populated when the activity is created. Note: the code snippets here are not tested but should give you a good idea of the general idea ;)

```php

// here more code about the model class using the Activity trait ...

     public function userRef()
    {
        return "SU:${userId}";
    }

    public function activityActorMethodName()
    {
        return 'userRef';
    }

// ...
```

The same thing can be achieved in a cleaner way by using the PHP client:

```php
$client->users()->createReference("john-doe");
```

You can retrieve the PHP client using the FeedManager facade:

```php
FeedManager::getClient
```

**Comment by azurinspire** [comment]
I think I tested that and got an exception because method declared in activityActorMethodName() should return instance of Eloquent relation, but I will test again.

**Comment by tbarbugli** [comment]
That is indeed very possible; an alternative approach is to implement `activityActor` for your model class. (and return the user ref as string)

**Comment by azurinspire** [comment]
That does the job, I didn't think at all to overwrite that one, thanks @tbarbugli
