### ISSUE TITLE
Call to undefined method GetStream\Stream\Feed::followFeed()

### ISSUE THREAD

**Issue by mkrakiewicz** [GetStream/stream-laravel#78]
Hi.
When I use `\FeedManager::followUser` in the most recent version I get:

```
In StreamLaravelManager.php line 93:
  Call to undefined method GetStream\Stream\Feed::followFeed()
```

It seems this method is removed in the most recent version.

**Comment by mkrakiewicz** [comment]
Also added a PR with proposed fix.

**Comment by tbarbugli** [comment]
Good catch, thank you for the fix!
