### ISSUE TITLE
Too many updates?

### ISSUE THREAD

**Issue by gelinger777** [GetStream/stream-laravel#98]
I have  setup a simple situation with following configuration 

```

    /*
    |-----------------------------------------------------------------------------
    | The feed that keeps content created by its author
    |-----------------------------------------------------------------------------
    |
    */
    'user_feed' => 'user',
    /*
    |-----------------------------------------------------------------------------
    | The feed containing notification activities
    |-----------------------------------------------------------------------------
    |
    */
    'notification_feed' => 'notification',
    /*
    |-----------------------------------------------------------------------------
    | The feeds that shows activities from followed user feeds
    |-----------------------------------------------------------------------------
    |
    */
    'news_feeds' => [
        'timeline' => 'timeline',
        'timeline_aggregated' => 'timeline_aggregated',
        'event'=>'event',
    
        'venue'=>'venue',
        
    ]
```

3-4 Follows of a user  has created 1400 feed updates. 

What can be the reason? 

Should I take out maybe  events and venues from the feed list in config? But even then it's quite strange that just 1 follow operation of another user creates such huge amount of feed updates...

I have used the code from your example 

```
$target_id = $request->input('target');
		$user_id = Auth::id();
		$params = array(
			'user_id' => Auth::id(),
			'target_id' => $target_id,
		);
		$follow = Follow::withTrashed()->where($params)->first();

		if ($follow === null) {
			$follow = new Follow($params);
			$follow->save();
			FeedManager::followUser($follow->user_id, $follow->target_id);
		} elseif ($follow->trashed()){
			$follow->restore();
			FeedManager::followUser($follow->user_id, $follow->target_id);
		}
		return Redirect::to($request->input('next'));
```

Any ideas what is wrong here?

**Comment by JimmyPettersson85** [comment]
Hi @gelinger777, do you have an appID? It's hard to do any investigation based on this info alone.

**Comment by gelinger777** [comment]
@JimmyPettersson85  AppID is 1244128

**Comment by JimmyPettersson85** [comment]
Hi! The bulk of your updates (> 1000) comes from unfollowing feeds which is a heavy write operation on our end and "costs" 25 updates per unfollow.

> The number of feed updates depends on how many activities you publish via the API and the number of users who follow those feeds. If you add an activity to a feed that is followed by 50 other feeds, this will trigger 51 feed updates. The only exception is unfollows. The unfollow operation is very heavy on our infrastructure and an additional 25 feed updates are billed for every unfollow operation.

https://support.getstream.io/hc/en-us/articles/360041929653-What-constitutes-an-update-Feeds

**Comment by gelinger777** [comment]
@JimmyPettersson85  I made only  like 20 follow/unfollow operations.  With one single user as "doer" . 

No other user was following the user who was performing the action. No other user was  following another user. I have just installed your example.

**Comment by gelinger777** [comment]
Right now I have in my config following setup 


```
    'news_feeds' => [
        'timeline' => 'timeline',
        'timeline_aggregated' => 'timeline_aggregated',
        'event'=>'event',
    
        'venue'=>'venue',
        
    ]

```
Right now we have following feeds in the Feed Group Sections
![image](https://user-images.githubusercontent.com/184276/235960064-1217cb13-82ca-4fb6-87c2-4ce090107010.png)

From what I understand from Logs, each time I click on Follow or Unfollow , laravel sends Follow and Unfollow on all Feed Groups in the config section. Then it makes sence. 

Maybe would be better if I explain what we want to achieve and you give some advise. 

We have user profiles ,artist profiles , events page in our app. An ordinary user can follow those pages, and have a newfeed. In the newfeed we would like to  Show upcoming events which friends(read followed users  by this particular user)  have saved  in their event list.  



So I guess we have to change the config to be 

```
 'news_feeds' => [
        'timeline' => 'timeline',
        'timeline_aggregated' => 'timeline_aggregated',
  
        
    ]

```
So USER 1 follow User 2 on  timeline  in timeline_aggregated  ?

Then what to do with Venues ? 

USER 2 follows  Venue 3
User 2 Follows  Venue 4
 

Then Venue 3 and 4 will show up in newfeed aggregated?

Sorry I am a bit confused with how the whole should work .

**Comment by JimmyPettersson85** [comment]
Hey @gelinger777

I'm sorry but I can't help you with integration questions here. My advise would be to read up on the [documentation](https://getstream.io/activity-feeds/docs/php/?language=php) and maybe play around with the pure [PHP SDK](https://github.com/GetStream/stream-php/) for starters to get more of an idea of whats going on. You are nowhere near reaching the limits on your account.

If you hit a brick wall there's always the [official support channels](https://getstream.io/contact/support/) to reach out to. Good luck!
